version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Pre-build phase
      - ls -al # List files in the current directory
      - pwd # Print the current working directory
      - find . -name "pom.xml" # Find the pom.xml file
  build:
    commands:
      - echo Build phase
      - cd $(find . -name "pom.xml" -exec dirname {} \;) # Change to the directory containing pom.xml
      - ls -al # List files to confirm we are in the correct directory
      - pwd # Print the current working directory
      - mvn clean install
      - ls -al target # List files in the target directory to confirm artifacts were generated
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - target/*.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes
